version: "3.3"
services:
  server: #all the ngnix container
    image: 'ngnix:stable-alpine'
    ports:
      - '8000:80' 
    volumes:
      - ./src:/var/www/html #means that server serves the request to the point
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro #bind mount for own configuration with read only
  php:
    build:
      context: ./dockerfiles #specify the folder of the dockerfile
      dockerfile: php.dockerfile
    volumes: 
      - ./src:/var/www/html:delegated #improve the performance of the container means whenever we changes some code in the file only reflected some batch
    
   
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/.mysql.env

  #utility container to run the docker file

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
        #artisian:
        #npm:
